#!/bin/bash
# 🚀 COMANDOS RÁPIDOS PARA DEPLOY A VERCEL

echo "==================================="
echo "  ONUS EXPRESS - DEPLOY A VERCEL"
echo "==================================="
echo ""

# OPCIÓN 1: VERCEL CLI (MÁS RÁPIDO)
echo "📦 OPCIÓN 1: Deploy Directo con Vercel CLI"
echo ""
echo "Paso 1: Instalar Vercel CLI"
echo "npm install -g vercel"
echo ""
echo "Paso 2: Login"
echo "vercel login"
echo ""
echo "Paso 3: Deploy a Producción"
echo "vercel --prod"
echo ""
echo "==================================="
echo ""

# OPCIÓN 2: GITHUB + VERCEL
echo "📦 OPCIÓN 2: Deploy via GitHub"
echo ""
echo "Paso 1: Inicializar Git"
echo "git init"
echo "git add ."
echo "git commit -m \"feat: Tarifario ONUS Express 2026 - Deploy inicial\""
echo "git branch -M main"
echo ""
echo "Paso 2: Conectar con GitHub"
echo "git remote add origin https://github.com/TU_USUARIO/onus-express-tarifarios.git"
echo "git push -u origin main"
echo ""
echo "Paso 3: Importar en Vercel"
echo "1. Ve a: https://vercel.com/dashboard"
echo "2. Click: Add New... → Project"
echo "3. Importa tu repositorio"
echo "4. Click: Deploy"
echo ""
echo "==================================="
echo ""

# VERIFICACIÓN
echo "✅ VERIFICACIÓN POST-DEPLOY"
echo ""
echo "1. Prueba la URL que Vercel te dio"
echo "2. Verifica funcionalidad:"
echo "   - Selección de vehículos"
echo "   - Cálculo de totales"
echo "   - Generación de PDF"
echo "   - Carga de logo cliente"
echo ""
echo "3. Test de rendimiento:"
echo "   https://pagespeed.web.dev/"
echo ""
echo "==================================="
echo ""
echo "🎉 ¡Listo para deployar!"
echo ""
